### ISSUE TITLE
脚本界面的中文会显示为乱码

### ISSUE THREAD

**Issue by NoHeartPen** [cweijan/vscode-autohotkey#76]
Sorry, my English is not very good, so the following English is translated by Google and may be difficult to understand.
(不好意思，我的英语不是很好，所以接下来的内容是基于Google翻译进行修改的，可能会比较难以理解)

When I double-click to run the script in the file manager, Chinese can be displayed.
(当我在文件管理器双击启动脚本，中文可以正常显示)
![image](https://user-images.githubusercontent.com/79316356/171643642-af3b30dc-0d14-4d3c-aa32-9ef12ccfca01.png)

But when I use the right mouse button and then click "Run Script" to run the script in VSCode,Chinese will be displayed incorrectly.
(而当我在VSCode内通过右键再点击"Run Script"来运行脚本的的话，会出现乱码)![image](https://user-images.githubusercontent.com/79316356/171644248-fad7fad4-d174-4659-9b1b-ba553da3b3fd.png)

I encountered this problem 2 weeks ago, and then I tried to search with keywords such as AHK, garbled characters, Chinese, etc., but none of them solved my problem. What should I do to display Chinese normally?
(我在2周以前遇到了该问题，之后尝试以AHK、乱码、中文等关键词进行过搜索，但都没有解决我的问题，请问我应该怎样做才能正常显示中文呢？)

Both VSCode and AutoHotKey is all up to date, but l still use Windows10, didn‘t upgrade to Windows11. 
(我的VSCode和AutoHotKey都是官网下载的最新版，但我使用的还是Win10操作系统)
AutoHotKey Version: 1.1.34.02
VSCode Version: 1.67.2
Windows: Window10 家庭中文版

**Comment by FuPeiJiang** [comment]
> Double-click to start the script in the file manager

Registry:
`HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.ahk`
`HKEY_LOCAL_MACHINE\SOFTWARE\Classes\AutoHotkeyScript\Shell\Open\Command`

`"C:\Program Files\AutoHotkey\AutoHotkey.exe" /CP65001 "%1" %*`

vscode: I don't know the command (because there are many buttons, which button did you click?)
, but I bet it's:
`"C:\Program Files\AutoHotkey\AutoHotkey.exe" "%1"`

and I forgot I was using a translator, that's cool

the fix: `settings.json`:
```json
"launch": {
    "version": "0.2.0",
    "configurations": [
      {
        "name": "AutoHotkey Debug",
        "type": "autohotkey",
        "request": "launch",
        "runtime_v1": "C:/Program Files/AutoHotkey/AutoHotkeyU64.exe",
        "runtime_v2": "C:/somewhere/AutoHotkey_2.0-beta.3/AutoHotkey64.exe",
        "runtimeArgs": [
          "/CP65001 /ErrorStdOut=UTF-8"
        ]
      },
    ]
}
```
requires: <https://marketplace.visualstudio.com/items?itemName=zero-plusplus.vscode-autohotkey-debug>
run using debugger, this is not 'run using triangle button'

**Comment by NoHeartPen** [comment]
Thanks for your suggestion. Now I use the translator and it can display chinese correctly.:)
![image](https://user-images.githubusercontent.com/79316356/171653590-be13a709-8b89-4a5f-ab8d-173af60f4e8d.png)
